version: '3.7'

services:

  grafana:
    image: jahrik/arm-grafana:armv7l
    networks:
      - traefik
      - monitor
    environment:
      GF_SECURITY_ADMIN_USER: "${ADMIN_USER:-admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SMTP_ENABLED: "${GF_SMTP_ENABLED:-false}"
      GF_SMTP_FROM_ADDRESS: "${GF_SMTP_FROM_ADDRESS:-grafana@test.com}"
      GF_SMTP_FROM_NAME: "${GF_SMTP_FROM_NAME:-Grafana}"
      GF_SMTP_HOST: "${GF_SMTP_HOST:-smtp:25}"
      GF_SMTP_USER: "${GF_SMTP_USER}"
      GF_SMTP_PASSWORD: "${GF_SMTP_PASSWORD}"
      GF_DATABASE_TYPE: "${GF_DATABASE_TYPE:-mysql}"
      GF_DATABASE_HOST: "${GF_DATABASE_HOST}"
      GF_DATABASE_USER: "${GF_DATABASE_USER}"
      GF_DATABASE_PASSWORD: "${GF_DATABASE_PASSWORD}"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.enable: 1
        traefik.port: 3000
        traefik.backend: grafana
        traefik.docker.network: traefik
        traefik.frontend.rule: Host:grafana.homelab.business
 
networks:
  monitor:
    name: monitor
    driver: overlay
    external: true
  traefik:
    name: traefik
    driver: overlay
    external: true
