version: '3.7'

services:

  grafana:
    image: "jahrik/grafana:${TAG}"
    networks:
      # - traefik
      - monitor
    environment:
      GF_SECURITY_ADMIN_USER: "${ADMIN_USER:-admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SMTP_ENABLED: "${GF_SMTP_ENABLED:-false}"
      GF_SMTP_FROM_ADDRESS: "${GF_SMTP_FROM_ADDRESS:-grafana@test.com}"
      GF_SMTP_FROM_NAME: "${GF_SMTP_FROM_NAME:-Grafana}"
      GF_SMTP_HOST: "${GF_SMTP_HOST:-smtp:25}"
      GF_SMTP_USER: "${GF_SMTP_USER}"
      GF_SMTP_PASSWORD: "${GF_SMTP_PASSWORD}"
      GF_DATABASE_TYPE: "${GF_DATABASE_TYPE:-mysql}"
      GF_DATABASE_HOST: "${GF_DATABASE_HOST}"
      GF_DATABASE_USER: "${GF_DATABASE_USER}"
      GF_DATABASE_PASSWORD: "${GF_DATABASE_PASSWORD}"
    deploy:
      mode: replicated
      replicas: 1
#       labels:
#         - traefik.enable=true
#         - traefik.network=traefik
#         - traefik.http.routers.grafana.tls=true
#         - traefik.http.routers.grafana.service=grafana
#         - traefik.http.routers.grafana.rule=Host(`grafana.homelab.business`)
#         - traefik.http.routers.grafana.middlewares=grafana-auth
#         - traefik.http.routers.grafana.entrypoints=web,websecure
#         - traefik.http.services.grafana.loadbalancer.server.port=3000
#         - traefik.http.middlewares.grafana-auth.basicauth.usersfile=/etc/traefik/.htpasswd

networks:
  monitor:
    name: monitor
    driver: overlay
    external: true
#   traefik:
#     name: traefik
#     driver: overlay
#     external: true
