version: '3'

services:

  grafana:
    image: jahrik/arm-grafana:arm32v7
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      # - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-localhost}
      # - GF_SMTP_ENABLED=${GF_SMTP_ENABLED:-false}
      # - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS:-grafana@test.com}
      # - GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME:-Grafana}
      # - GF_SMTP_HOST=${GF_SMTP_HOST:-smtp:25}
      # - GF_SMTP_USER=${GF_SMTP_USER}
      # - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
    volumes:
      - /mnt/g2/grafana:/data:rw
    deploy:
      mode: replicated
      replicas: 1
